### ISSUE TITLE
Looks like syntax issue which is breaking the lua compilation,

### ISSUE THREAD

**Issue by babula38** [MoaidHathot/Neovim-Moaid#1]
https://github.com/MoaidHathot/Neovim-Moaid/blob/1521145beb1f0567b915675f863594fe083d66fd/config/nvim/lua/moaid/keymap.lua#L85C1-L85C89

**Comment by MoaidHathot** [comment]
Thanks @babula38 for pointing that out. It should be fixed now with commit 874dc10

**Comment by babula38** [comment]
Thanks
