### ISSUE TITLE
lacks installation instructions for linux

### ISSUE THREAD

**Issue by Vinni-Cedraz** [MoaidHathot/Neovim-Moaid#3]

**Comment by MoaidHathot** [comment]
@Vinni-Cedraz, I don't have a Linux machine. The configuration should work in Linux as well, but I didn't try it.
I can help you or someone else troubleshoot issues on Linux so we can write the instructions.

**Comment by MoaidHathot** [comment]
@Vinni-Cedraz I added instructions for Linux :)

**Comment by Vinni-Cedraz** [comment]
You mean, for linux? Cool will try. Thanks!

**Comment by MoaidHathot** [comment]
@Vinni-Cedraz, yes, for Linux. I had a typo (fixed now) 😅
